services:
  securecapita:
    container_name: tasker_backend
    build: .
    image: tasker_backend
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - net1

networks:
  net1:
    name: frontend_internalnet
    external: true
